pipeline {
    agent any

    environment {
        S3_BUCKET = "aakda.in"
        CLOUDFRONT_DISTRIBUTION_ID = "E3IBFDRZWZW825"
        AWS_DEFAULT_REGION = "ap-south-1"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh '''
                    rm -rf node_modules
                    rm -f package-lock.json
                    npm cache clean --force
                    npm install
                    npm install gensync --save-dev
                    npm ls gensync
                    '''
                }
            }
        }

        stage('Copy ENV') {
            steps {
                sh '''
                cp /var/www/Aakda/Games/frontend/.env frontend/.env
                '''
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                dir('frontend') {
                    sh '''
                    aws s3 sync dist/ s3://$S3_BUCKET --delete
                    '''
                }
            }
        }

        stage('Invalidate CloudFront Cache') {
            steps {
                sh '''
                aws cloudfront create-invalidation \
                --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
                --paths "/*"
                '''
            }
        }

    }
}