pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                sh '''
                sudo rsync -av --delete \
                --chown=ubuntu:devops \
                --exclude='.env' \
                backend/ /var/www/Aakda/Games/backend/
                '''
            }
        }

        stage('Reload Backend') {
            steps {
                sh '''
                cd /var/www/Aakda/Games/backend

                pm2 reload ecosystem.config.cjs --only games-backend --update-env || \
                pm2 start ecosystem.config.cjs --only games-backend

                sleep 10

                curl --fail http://localhost:4000/health
                '''
            }
        }
    }
}