pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                sh '''
                sudo rsync -av --delete \
                --chown=ubuntu:devops \
                --exclude='.env' \
                backend/ /var/www/Aakda/Games/backend/
                '''
            }
        }

        stage('Restart Backend') {
            steps {
                sh '''
                pm2 restart games-backend || pm2 start /var/www/Aakda/Games/backend/index.js --name games-backend
                '''
            }
        }
    }
}