/**
 * External games configuration.
 * Add new games here - each opens in a new tab.
 * url: full URL (use {{userId}} to inject logged-in user ID if needed)
 */
export const GAMES = [
  {
    id: 'aviator',
    name: 'Aviator',
    description: 'Crash Game',
    icon: '✈️',
    highEarning: true,
    image: 'https://res.cloudinary.com/dnyp5jknp/image/upload/v1771335934/Aviator_Games_aqtqig.svg',
    url: 'https://aviator-jet-theta.vercel.app/?uid=68c3b5afbc7114822c777c1b',
    external: true,
  },
  {
    id: 'across-universe',
    name: 'Across the Universe',
    description: 'Adventure Game',
    icon: '🌌',
    highEarning: true,
    image: 'https://res.cloudinary.com/dnyp5jknp/image/upload/v1771700000/across_universe_game_placeholder.jpg',
    url: null,
    external: false,
    upcoming: true,
  },
  {
    id: 'aqua-moto-racing',
    name: 'Aqua Moto Racing',
    description: 'Racing Game',
    icon: '🏄',
    highEarning: true,
    image: 'https://res.cloudinary.com/dnyp5jknp/image/upload/v1771700001/aqua_racing_game_placeholder.jpg',
    url: null,
    external: false,
    upcoming: true,
  },
  {
    id: 'bear-run',
    name: 'Bear Run',
    description: 'Running Game',
    icon: '🐻',
    highEarning: true,
    image: 'https://res.cloudinary.com/dnyp5jknp/image/upload/v1771700002/bear_run_game_placeholder.jpg',
    url: null,
    external: false,
    upcoming: true,
  },
  {
    id: 'bonus-time',
    name: 'Bonus Time',
    description: 'Slot Game',
    icon: '🎰',
    highEarning: true,
    image: 'https://res.cloudinary.com/dnyp5jknp/image/upload/v1771700003/bonus_time_game_placeholder.jpg',
    url: null,
    external: false,
    upcoming: true,
  },
  {
    id: 'bucking-rider',
    name: 'Bucking Rider',
    description: 'Action Game',
    icon: '🤠',
    highEarning: true,
    image: 'https://res.cloudinary.com/dnyp5jknp/image/upload/v1771700004/bucking_rider_game_placeholder.jpg',
    url: null,
    external: false,
    upcoming: true,
  },
];
