pipeline {
    agent any

    environment {
        S3_BUCKET = "shriganesh.fun"
        CLOUDFRONT_DISTRIBUTION_ID = "E2HBGUF3RNOPLT"
        AWS_DEFAULT_REGION = "ap-south-1"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('admin') {
                    sh 'npm install'
                }
            }
        }

        stage('Copy ENV') {
            steps {
                sh '''
                cp /var/www/Aakda/Games/admin/.env admin/.env
                '''
            }
        }

        stage('Build Admin') {
            steps {
                dir('admin') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                dir('admin') {
                    sh '''
                    aws s3 sync dist/ s3://$S3_BUCKET --delete
                    '''
                }
            }
        }

        stage('Invalidate CloudFront Cache') {
            steps {
                sh '''
                aws cloudfront create-invalidation \
                --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
                --paths "/*"
                '''
            }
        }
    }
}